# Generated by Django 4.2 on 2023-04-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('disp_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Display Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('c_phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Cell Phone')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6, verbose_name='Room Number')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Therapists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('disp_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Display Name')),
                ('studentID', models.CharField(max_length=10, verbose_name='Student ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('c_phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Cell Phone')),
                ('schedule', models.DateTimeField(verbose_name='Schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Apptmnts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_date', models.DateTimeField(verbose_name='Appointment Date')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.clients')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.rooms')),
                ('therapist_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='website.therapists')),
            ],
        ),
    ]
