# Generated by Django 4.2 on 2023-04-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapists',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Schedule'),
        ),
    ]
