# Generated by Django 4.2 on 2023-04-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_therapists_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('disp_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Display Name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('c_phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='Cell Phone')),
            ],
        ),
    ]
